##
## Makefile for lkm-syscall**
##
## Originally made by xsyann
## Contact <contact@xsyann.com>
##
## Current version built by Yuan Xiao
## Contact <xiao.465@osu.edu>


all:
	cd lkm; make
	cd test; make

clean:
	cd lkm; make clean
	cd test; make clean
